index:
    path: /
    controller: App\Controller\PageController::indexAction
    requirements:
         methods:  GET
about:
  path:   /about
  controller:  App\Controller\PageController::aboutAction
  requirements:
    methods:  GET
contact:
  path:  /contact
  controller:  App\Controller\PageController::contactAction
  requirements:
    methods:  GET|POST
blog_show:
  path:  /{id}/{slug}
  controller:  App\Controller\BlogController::showAction
  requirements:
    methods:  GET
    id: \d+
comment_create:
  path:  /comment/{blog_id}
  controller:  App\Controller\CommentController:createAction
  requirements:
    methods:  POST
    blog_id: \d+
